### PR TITLE
Revert "C13970: Extra hyperlink due to potential incorrect structure"

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Reverts MicrosoftDocs/biztalk-docs#201

Hello, @MandiOhlinger, 

This PR was opened to look for a fix. There is an extra hyperlink on target versions due to potential incorrect structure. Could you, please, verify the strucuturesin lines 183 and 184? Please, refer yo the image attached for further details. Many thanks in advance for your time.

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/walkthrough-testing-the-policy.md](https://github.com/carolinacmoravia/biztalk-docs/blob/revert-201-patch-22/biztalk/core/walkthrough-testing-the-policy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/walkthrough-testing-the-policy?branch=pr-en-us-205) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C16%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201804161534353528-205%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ERvRlP63rA5UIJnsDukCNMxjh6lbo451SzXCqV5rcYc%3D&st=2018-04-16T15%3A32%3A56Z&se=2018-05-17T15%3A37%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by carolinacmoravia** [comment]
Hello, @MandiOhlinger,

This PR was opened to look for a fix. There is an extra hyperlink on target versions due to potential incorrect structure. Could you, please, verify the strucuturesin lines 183 and 184? Please, refer yo the image attached for further details. Many thanks in advance for your time.

**Comment by MandiOhlinger** [comment]
@carolinacmoravia I can't confirm this. I don't know what the text was before the markdown migration.

**Comment by carolinacmoravia** [comment]
Hello, @MandiOhlinger,

Thanks for your comment. I close this PR since loc team address this issue from their side properly. 

Thanks for your time!

**Pull request closed without merging**
