### PR TITLE
Fix to broken link for "Create the SSIS Catalog"

### PR DESCRIPTION
**Pull request by CarloGarcia**
Link was this (which now gives 404 error):
https://docs.microsoft.com/en-us/sql/integration-services/create-the-ssis-catalog

Updated to this.
https://docs.microsoft.com/en-us/sql/integration-services/catalog/ssis-catalog?view=sql-server-ver15#create-the-ssis-catalog

### CODE REVIEW

**Comment by CarloGarcia** [comment]
This is a fix for issue #567 

https://github.com/MicrosoftDocs/biztalk-docs/issues/567

**Comment by CarloGarcia** [comment]
@MandiOhlinger - Would you be available to review this PR?

**Comment by MandiOhlinger** [comment]
@CarloGarcia Thank you very much! I removed the language identifiers from the URL. So, we're good to merge.

**Comment by CarloGarcia** [comment]
Thank you Mandi!

**Pull request merged**
