### PR TITLE
chore: Renormailze line endings

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[e30e5fd](https://github.com/nschonni/biztalk-docs/pull/404/commits/e30e5fdfa23289201e84bef3d1cf44be44b39f27)_: 

:clock10: **Full build**: the average full build time is _8 min(s) 57 sec(s)_, this is based on the last _8_ build(s) for this repository.

 :warning: **This is a FULL build** due to a recent Docs Build service upgrade, normally no action is required on your part. In the result you find subsequent builds still performing full builds, please contact your repository admin to manually perform a full build on the 'master' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[e30e5fd](https://github.com/nschonni/biztalk-docs/pull/404/commits/e30e5fdfa23289201e84bef3d1cf44be44b39f27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.redirection.json](https://github.com/nschonni/biztalk-docs/blob/chore--Renormailze-line-endings/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[biztalk/core/office365-adapters.md](https://github.com/nschonni/biztalk-docs/blob/chore--Renormailze-line-endings/biztalk/core/office365-adapters.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/office365-adapters?branch=pr-en-us-404) |
[biztalk/core/office365-calendar-adapter.md](https://github.com/nschonni/biztalk-docs/blob/chore--Renormailze-line-endings/biztalk/core/office365-calendar-adapter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/office365-calendar-adapter?branch=pr-en-us-404) |
[biztalk/core/office365-contact-adapter.md](https://github.com/nschonni/biztalk-docs/blob/chore--Renormailze-line-endings/biztalk/core/office365-contact-adapter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/office365-contact-adapter?branch=pr-en-us-404) |
[biztalk/core/office365-mail-adapter.md](https://github.com/nschonni/biztalk-docs/blob/chore--Renormailze-line-endings/biztalk/core/office365-mail-adapter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/office365-mail-adapter?branch=pr-en-us-404) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C24%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201906240603532588-404%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JlcmgEO2XeIYQdhPTxI1l3BW8yvPfg%2BShTYVEu23Mqk%3D&st=2019-06-24T06%3A09%3A56Z&se=2019-07-25T06%3A14%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Closing w/o merging. Can't tell the exact changes made.

**Comment by nschonni** [comment]
Currently the line endings in these files don't match what is in the .gitignore
If you want to run it yourself, you can as described here https://stackoverflow.com/a/47580886/455535 with `git add --renormalize .`

**Pull request closed without merging**
