### PR TITLE
Update update-references-to-bam-primary-import-database-name-and-conn…

### PR DESCRIPTION
**Pull request by bcks14**
…ection-string.md

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string.md](https://github.com/bcks14/biztalk-docs/blob/patch-1/biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string?branch=pr-en-us-178) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201802012004105249-178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=d%2FvNGNs1wciK3LSBFucNHM5ZU%2F%2F6SIGTMhpLvmcGKwQ%3D&st=2018-02-01T20%3A01%3A35Z&se=2018-03-04T20%3A06%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bcks14** [comment]
@MandiOhlinger

**Comment by bcks14** [comment]
@MandiOhlinger

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string.md](https://github.com/bcks14/biztalk-docs/blob/patch-1/biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string?branch=pr-en-us-178) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201802012012214812-178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GVczejx9hRnOPwXgpdtOTRPNvyB8dKw%2FHTQoWoK7NuY%3D&st=2018-02-01T20%3A09%3A58Z&se=2018-03-04T20%3A14%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string.md](https://github.com/bcks14/biztalk-docs/blob/patch-1/biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/update-references-to-bam-primary-import-database-name-and-connection-string?branch=pr-en-us-178) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201802012050414406-178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Y%2Fl%2B9YP0cG4a34PCRi0QHbbDoudMfw5bjMTOFq5bxRc%3D&st=2018-02-01T20%3A48%3A25Z&se=2018-03-04T20%3A53%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
