### PR TITLE
User story #1571029; fix asterisks

### PR DESCRIPTION
**Pull request by jameshkramer**
Changes for User Story 1571029.

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[25f1c4a](https://github.com/jameshkramer/biztalk-docs/pull/424/commits/25f1c4a3b9fe8a00a54d7f568da3d86914b4333b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md](https://github.com/jameshkramer/biztalk-docs/blob/#1571029-fix-asterisks%5Cbiztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013?branch=pr-en-us-424) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C30%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201907292358222728-424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=We6xLov3XhFfYNVp3vyPwG%2BcV6DlX3ihbc9%2BuAEojio%3D&st=2019-07-29T23%3A57%3A04Z&se=2019-08-30T00%3A02%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@jameshkramer Any reason why you closed this?

**Comment by jameshkramer** [comment]
@MandiOhlinger  @tfosmark @LizCasey 

Hi Mandi,

It’s great to hear from you, because I am pretty confused.

It is the issue of what repo to use. I contributed to biztalk-docs because it is specified in the work item (https://dev.azure.com/mseng/TechnicalContent/_queries/edit/1571029/?triage=true). After I created the PR, I discovered that there is a biztalks-docs-pr on Azure DevOps (https://dev.azure.com/mseng/TechnicalContent/_git/biztalk-docs-pr?path=%2F&version=GBmaster) . My boss, Tami Fosmark, said that that is what I should use, so I have been trying to figure that out, with little luck. From what I can tell, no one has been using it to publish.

So, would you please advise me? I'll reopen this PR if that is the right thing

Thanks,

Jim

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[25f1c4a](https://github.com/jameshkramer/biztalk-docs/pull/424/commits/25f1c4a3b9fe8a00a54d7f568da3d86914b4333b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md](https://github.com/jameshkramer/biztalk-docs/blob/#1571029-fix-asterisks%5Cbiztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013?branch=pr-en-us-424) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C7%5C31%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201907311725182807-424%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IkEfn5jLSRBCT8q0WjCS6Gdduj8pyD4X5ydgjY6KavM%3D&st=2019-07-31T17%3A24%3A21Z&se=2019-08-31T17%3A29%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tfosmark** [comment]
@MandiOhlinger We typically work in private repos, but if you're good with the changes, no reason not to merge if no additional validation is helpful. :-) Thanks!

**Comment by jameshkramer** [comment]
@MandiOhlinger, can you give me an idea of when #424 will be merged? @ishasahni1 asked about it, so perhaps it is a matter of some urgency for her. My bosses (@tfosmark @LizCasey) and I are interested, also.

Thanks,

Jim

cc: @tfosmark @LizCasey

**Comment by tfosmark** [comment]
@jameshkramer Jim, can you also fix the italics at the end of each cell? Change this:

> The names of the DLLs are:<br /><br /> - \*\*For 32-bit\*<em>: gsskrb5.dll, gssntlm.dll<br /><br /> -  \*\*For 64-bit x86\*</em>: gx64krb5.dll, gx64ntlm.dll

...to this:

> The names of the DLLs are:<br /><br /> - \*\*For 32-bit\*:<em> gsskrb5.dll, gssntlm.dll</em><br /><br /> -  \*\*For 64-bit x86\*:<em> gx64krb5.dll, gx64ntlm.dll</em>

Thanks.

**Pull request closed without merging**
