### PR TITLE
new his hub page

### PR DESCRIPTION
**Pull request by v-savila**
for bug 1170408

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[his/index.md](https://github.com/MicrosoftDocs/biztalk-docs/blob/1170408/his/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/his/index?branch=pr-en-us-173) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C26%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201801261850216699-173%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZuUnUiduO4eI%2BjDj4MOzWVbKHTIitIqWOX%2BEyAGS9fo%3D&st=2018-01-26T18%3A48%3A19Z&se=2018-02-26T18%3A53%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[his/index.md](https://github.com/MicrosoftDocs/biztalk-docs/blob/1170408/his/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/his/index?branch=pr-en-us-173) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C2%5C1%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201802011742558540-173%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8p8PwfsgoSYKnEBG5ARXJb13K%2BAlemvz6JKYSU7YJ4Q%3D&st=2018-02-01T17%3A40%3A58Z&se=2018-03-04T17%3A45%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@v-savila This looks great. Thank you. If you're OK with it, I'll merge it ASAP.

**Comment by v-savila** [comment]
@MandiOhlinger sure, please mere this PR.

**Pull request merged**
