### PR TITLE
pages without ms.prod

### PR DESCRIPTION
**Pull request by v-kents**
This one is just adding the ms.prod to pages without

### CODE REVIEW

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment?branch=pr-en-us-53) |
[biztalk/core/configure-the-json-template-for-automatic-deployment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/configure-the-json-template-for-automatic-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-the-json-template-for-automatic-deployment?branch=pr-en-us-53) |
[biztalk/core/connect-to-azure-api-management.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/connect-to-azure-api-management.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/connect-to-azure-api-management?branch=pr-en-us-53) |
[biztalk/dev-center/biztalk-server-code-samples.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/dev-center/biztalk-server-code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/dev-center/biztalk-server-code-samples?branch=pr-en-us-53) |
[biztalk/dev-center/learn-biztalk-server.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/dev-center/learn-biztalk-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/dev-center/learn-biztalk-server?branch=pr-en-us-53) |
[biztalk/index.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/index?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/install-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/install-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/install-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/technical-guides/biztalk-technical-guides.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/technical-guides/biztalk-technical-guides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/technical-guides/biztalk-technical-guides?branch=pr-en-us-53) |
[biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized?branch=pr-en-us-53) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C6%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201709062129424702-53%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment?branch=pr-en-us-53) |
[biztalk/core/configure-the-json-template-for-automatic-deployment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/configure-the-json-template-for-automatic-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-the-json-template-for-automatic-deployment?branch=pr-en-us-53) |
[biztalk/core/connect-to-azure-api-management.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/connect-to-azure-api-management.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/connect-to-azure-api-management?branch=pr-en-us-53) |
[biztalk/dev-center/biztalk-server-code-samples.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/dev-center/biztalk-server-code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/dev-center/biztalk-server-code-samples?branch=pr-en-us-53) |
[biztalk/dev-center/learn-biztalk-server.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/dev-center/learn-biztalk-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/dev-center/learn-biztalk-server?branch=pr-en-us-53) |
[biztalk/docfx.json](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/docfx.json) | :white_check_mark:Succeeded | |
[biztalk/index.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/index?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/install-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/install-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/install-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/technical-guides/biztalk-technical-guides.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/technical-guides/biztalk-technical-guides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/technical-guides/biztalk-technical-guides?branch=pr-en-us-53) |
[biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized?branch=pr-en-us-53) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C6%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201709062139070561-53%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
I found some issues on the index page:

**Get Started**: The B2B link is incorrect. It should be: https://review.docs.microsoft.com/en-us/biztalk/core/trading-partner-management-using-biztalk-server

**Announcements & social media**: The following Twitter links aren't working: 

- #msbts should be: https://twitter.com/hashtag/msbts
- BizTalk Gurus should be: https://twitter.com/BizTalkGurus

**Developers** tab at the top: The Five Day course on GitHub link should be: https://github.com/wmmihaa/BizTalk-Server---Developing-Integration-Solutions

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-environmental-tokens-and-variables-for-automatic-deployment?branch=pr-en-us-53) |
[biztalk/core/configure-the-json-template-for-automatic-deployment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/configure-the-json-template-for-automatic-deployment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-the-json-template-for-automatic-deployment?branch=pr-en-us-53) |
[biztalk/core/connect-to-azure-api-management.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/core/connect-to-azure-api-management.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/connect-to-azure-api-management?branch=pr-en-us-53) |
[biztalk/dev-center/biztalk-server-code-samples.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/dev-center/biztalk-server-code-samples.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/dev-center/biztalk-server-code-samples?branch=pr-en-us-53) |
[biztalk/dev-center/learn-biztalk-server.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/dev-center/learn-biztalk-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/dev-center/learn-biztalk-server?branch=pr-en-us-53) |
[biztalk/docfx.json](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/docfx.json) | :white_check_mark:Succeeded | |
[biztalk/index.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/index?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-2013-and-2013-r2-what-s-new-install-and-upgrade?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-2016-what-s-new-and-installation?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/biztalk-server-what-s-new-installation-configuration-and-upgrade?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/install-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/install-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/install-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/post-configuration-steps-to-optimize-your-environment?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/upgrade-to-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/what-s-new-in-biztalk-server-2016?branch=pr-en-us-53) |
[biztalk/technical-guides/biztalk-technical-guides.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/technical-guides/biztalk-technical-guides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/technical-guides/biztalk-technical-guides?branch=pr-en-us-53) |
[biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized.md](https://github.com/v-kents/biztalk-docs/blob/users/v-kents/home/biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/technical-guides/mscit-supply-chain-migration-from-biztalk-2009-to-biztalk-2013-r2-virtualized?branch=pr-en-us-53) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C6%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201709062216398036-53%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
