### PR TITLE
Fixed 2 incorrect paths to bm.exe

### PR DESCRIPTION
**Pull request by clineer**
@MandiOhlinger, I found two places where an include file is used to output the path for BizTalk but it is missing the trailing slash and it causes the output to have an incorrect path. It outputs "BizTalk Server Tracking" but it should be "BizTalk Server\Tracking". I left the include file alone and implemented the fix around the include file. 

If you would prefer I update the include file, please let me know and I can create a new PR. I did not want to possibly break something else that might refer to the include file so I left the include file alone. 

Thanks,
Ben Cline

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[803f4ef](https://github.com/clineer/biztalk-docs/commits/803f4efbf4ac306a26c0c23a62df288d7dfba2e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-configure-a-workflow-foundation-application-for-interception.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/core/how-to-configure-a-workflow-foundation-application-for-interception.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-configure-a-workflow-foundation-application-for-interception?branch=pr-en-us-444) |
[biztalk/core/update-the-bam-management-utility-configuration-after-a-backup-and-restore.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/core/update-the-bam-management-utility-configuration-after-a-backup-and-restore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/update-the-bam-management-utility-configuration-after-a-backup-and-restore?branch=pr-en-us-444) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C4%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201909041951163949-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wXmlxRdW49BJjkRrQpeVORqUkC%2Bs0NY4mORZge%2B%2F6gc%3D&st=2019-09-04T19%3A50%3A07Z&se=2019-10-05T19%3A55%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[6c07b23](https://github.com/clineer/biztalk-docs/commits/6c07b23448afb7c0dc6d3c8ae70870e32ae0fc7b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/accelerator-rosettanet/working-with-the-tracking-activity-definition-file.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/adapters-and-accelerators/accelerator-rosettanet/working-with-the-tracking-activity-definition-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/accelerator-rosettanet/working-with-the-tracking-activity-definition-file?branch=pr-en-us-444) |
[biztalk/core/how-to-configure-a-workflow-foundation-application-for-interception.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/core/how-to-configure-a-workflow-foundation-application-for-interception.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-configure-a-workflow-foundation-application-for-interception?branch=pr-en-us-444) |
[biztalk/core/update-the-bam-management-utility-configuration-after-a-backup-and-restore.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/core/update-the-bam-management-utility-configuration-after-a-backup-and-restore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/update-the-bam-management-utility-configuration-after-a-backup-and-restore?branch=pr-en-us-444) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C4%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201909042048030408-444%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V0HDgM4ysv7ND0dnwU5h9wRElDCe7SckGMk6Eapl0aM%3D&st=2019-09-04T20%3A47%3A08Z&se=2019-10-05T20%3A52%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clineer** [comment]
It looks like the closed pull request change is on this PR now. I will not make a new one now. Thanks

**Comment by MandiOhlinger** [comment]
@clineer Thank you for fixing that path.

**Comment by clineer** [comment]
@MandiOhlinger No problem. I realize now probably the issue happened when the article was switched to use the include.

**Pull request merged**
