### PR TITLE
Update how-to-configure-iis-for-an-http-receive-location.md

### PR DESCRIPTION
**Pull request by emielkool**
Add note for Enable 32-Bit Application setting on AppPool

### CODE REVIEW

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-configure-iis-for-an-http-receive-location.md](https://github.com/emielkool/biztalk-docs/blob/patch-1/biztalk/core/how-to-configure-iis-for-an-http-receive-location.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-configure-iis-for-an-http-receive-location?branch=pr-en-us-76) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C5%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201710051346024557-76%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OrfJujqmqppt9XjMIcHXUCA8NJJ28corbxH6uR7qZ9s%3D&st=2017-10-05T13%3A43%3A45Z&se=2017-10-06T13%3A53%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-configure-iis-for-an-http-receive-location.md](https://github.com/emielkool/biztalk-docs/blob/patch-1/biztalk/core/how-to-configure-iis-for-an-http-receive-location.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-configure-iis-for-an-http-receive-location?branch=pr-en-us-76) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201710060659242203-76%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PPNcuJ3%2FwQ6fboh%2BPLPL42xwLyFAgGJJ3ChTgpDb7Is%3D&st=2017-10-06T06%3A57%3A02Z&se=2017-10-07T07%3A07%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-configure-iis-for-an-http-receive-location.md](https://github.com/emielkool/biztalk-docs/blob/patch-1/biztalk/core/how-to-configure-iis-for-an-http-receive-location.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-configure-iis-for-an-http-receive-location?branch=pr-en-us-76) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C10%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201710100035338375-76%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4NTYPnQ91aOqqMBcWNPr%2FX7wJoCXckaakHfGCVr%2FW8w%3D&st=2017-10-10T00%3A32%3A41Z&se=2017-11-10T00%3A37%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@emielkool Thank you for updating this topic, and keep them coming. I stepped through it, and updated the steps (it was very outdated). Can you sign the contributor license? Then, we can get this PR merged. Once signed, you won't need to sign again, and you'll be all set for future contributions.

**Pull request merged**
