### PR TITLE
C116015: Fixing asterisks issues to avoid broken content in live pages

### PR DESCRIPTION
**Pull request by v-maudel**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: Several asterisks issues in live pages regarding bad formatting.

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[b2830a8](https://github.com/v-maudel/biztalk-docs/commits/b2830a896bf7e52ee572ca4eefadeb3a29fa5a22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md](https://github.com/v-maudel/biztalk-docs/blob/patch-13/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013?branch=pr-en-us-449) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C9%5C17%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201909171439330604-449%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TJbX2f19o9eVuoPKUWWG4dYiwp7NMDPNc%2BubfFmAGWM%3D&st=2019-09-17T14%3A38%3A32Z&se=2019-10-18T14%3A43%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-maudel** [comment]
Hi @MandiOhlinger, could you please merge this PR?
Thanks in advance

**Comment by v-maudel** [comment]
Hi @MandiOhlinger, could you please merge this PR?
Thanks in advance

**Comment by v-maudel** [comment]
Created new PR here due merge conflicts: https://github.com/MicrosoftDocs/biztalk-docs/pull/458

**Pull request closed without merging**
