### PR TITLE
Update configure-the-operational-data-feed-for-power-bi-with-biztalk-…

### PR DESCRIPTION
**Pull request by sandroasp**
Adding more information to the documentation, fixing some invalid information to correct BizTalkOperationalDataService intead of OperationalDataService.

### CODE REVIEW

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/configure-the-operational-data-feed-for-power-bi-with-biztalk-server.md](https://github.com/sandroasp/biztalk-docs/blob/patch-14/biztalk/core/configure-the-operational-data-feed-for-power-bi-with-biztalk-server.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/configure-the-operational-data-feed-for-power-bi-with-biztalk-server?branch=pr-en-us-85) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C11%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201710112119267169-85%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wNLNqNikpTCXQApXjGRz%2F8sg5hd2JjUTbaatbBHovTo%3D&st=2017-10-11T21%3A17%3A05Z&se=2017-11-11T21%3A22%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@sandroasp I'm going to be rewriting/updating the FP1 docs next week (to get ready for FP2). I'll keep this PR on hold to make sure we're not duplicating efforts. Thanks for all you do; it is very much appreciated.

**Comment by MandiOhlinger** [comment]
Hey @sandroasp - I updated/published https://docs.microsoft.com/biztalk/core/configure-the-operational-data-feed-for-power-bi-with-biztalk-server, which conflicts with some of the changes you made. Take a look at the recent updates, and feel free to add anything. Have I said how awesome you are today?

**Comment by MandiOhlinger** [comment]
Changes in newer PRs. Closing.

**Pull request closed without merging**
