### PR TITLE
wrap schema URLs in code blocks

### PR DESCRIPTION
**Pull request by v-kents**

### CODE REVIEW

**Comment by v-kents** [comment]
@MandiOhlinger All cleaned up and ready to merge.

**Comment by MandiOhlinger** [comment]
@v-kents Hey Kent - It looks like the tooling adding extra code blocks when there's a hashtag in the URL. I sent you an email with the specifics.

**Comment by v-kents** [comment]
@MandiOhlinger Fixed those - for example https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/accelerator-hl7/acknowledgments-known-issues?branch=pr-en-us-611

**Comment by MandiOhlinger** [comment]
@v-kents It removed the leading and trailing `<>` from the URLs:

Was: **<http://microsoft.com/HealthCare/HL7/2X#ACK_25_GLO_DEF>.**
Currently: `http://microsoft.com/HealthCare/HL7/2X#ACK_25_GLO_DEF`
Should be: `<http://microsoft.com/HealthCare/HL7/2X#ACK_25_GLO_DEF>`

**Comment by v-kents** [comment]
@MandiOhlinger Really? That seems odd - I thought it was an error in the pages. Is that how Biztalk expects it?

**Comment by v-kents** [comment]
@MandiOhlinger OK, angle brackets re-removed :)

**Pull request merged**
