### PR TITLE
Added EsbItineraryDb and EsbExceptionDb Role location

### PR DESCRIPTION
**Pull request by skastberg**
Added EsbItineraryDb and EsbExceptionDb Role location, Tracking is the Role where this databases should be added.

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/high-availability-using-sql-server-always-on-availability-groups.md](https://github.com/skastberg/biztalk-docs/blob/EsbDatabases-In-AG/biztalk/core/high-availability-using-sql-server-always-on-availability-groups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/high-availability-using-sql-server-always-on-availability-groups?branch=pr-en-us-156) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C5%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201712052343329619-156%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KZLDtWWiagOpgt0QqkxH5DiwvQWsMMJlaZYPejNclaE%3D&st=2017-12-05T23%3A49%3A56Z&se=2018-01-05T23%3A54%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@skastberg Thank you. Can you submit this PR to the Live branch (instead of Master)?

**Comment by skastberg** [comment]
@MandiOhlinger Should I alway go towards Live?

**Comment by MandiOhlinger** [comment]
@skastberg For small updates like this, yes, Live is fine. We're also doing a lot of work in Master, so it'll be awhile before any Master updates are merged to Live.

**Comment by MandiOhlinger** [comment]
Closing PR as changes were made in Live branch.

**Pull request closed without merging**
