### PR TITLE
Typo in article

### PR DESCRIPTION
**Pull request by clineer**
@mandiohlinger, I found a typo in the article when reading over it. The word "and" was entered like this "an	d". Thanks, Ben Cline

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[c55a536](https://github.com/clineer/biztalk-docs/pull/408/commits/c55a536ca4b048b11217d2240f249afc90c5c2ca)_: 

:clock10: **Full build**: the average full build time is _9 min(s) 3 sec(s)_, this is based on the last _13_ build(s) for this repository.

 :warning: **This is a FULL build** due to a recent Docs Build service upgrade, normally no action is required on your part. In the result you find subsequent builds still performing full builds, please contact your repository admin to manually perform a full build on the 'master' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by clineer** [comment]
Thanks Mandi!

**Comment by clineer** [comment]
Sorry Mandi, I accidentally closed it. I reopened it. What is the next step for this?

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[c55a536](https://github.com/clineer/biztalk-docs/pull/408/commits/c55a536ca4b048b11217d2240f249afc90c5c2ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/logic-app-adapter.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/core/logic-app-adapter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/logic-app-adapter?branch=pr-en-us-408) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C25%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201906251912323846-408%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6Xlt5IAU4lj%2BLXJO92CCgQf8Vp840xYZD24N5t13700%3D&st=2019-06-25T19%3A17%3A16Z&se=2019-07-26T19%3A22%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[c55a536](https://github.com/clineer/biztalk-docs/pull/408/commits/c55a536ca4b048b11217d2240f249afc90c5c2ca)_: 

:clock10: **Full build**: the average full build time is _9 min(s)_, this is based on the last _14_ build(s) for this repository.

 :warning: **This is a FULL build** due to a recent Docs Build service upgrade, normally no action is required on your part. In the result you find subsequent builds still performing full builds, please contact your repository admin to manually perform a full build on the 'master' branch. For more detailed info, please click [here](https://aka.ms/full-build-reasons).

**Comment by MandiOhlinger** [comment]
@clineer You're all done. When the build completes, I'll get it merged. Thanks again! Feel free to create more PRs :).

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[c55a536](https://github.com/clineer/biztalk-docs/pull/408/commits/c55a536ca4b048b11217d2240f249afc90c5c2ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/logic-app-adapter.md](https://github.com/clineer/biztalk-docs/blob/master/biztalk/core/logic-app-adapter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/logic-app-adapter?branch=pr-en-us-408) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C25%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201906251921326273-408%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FGVo62fjnwETfnX9xYEidbNCPsIfc7a%2BXfhrZn4BnFM%3D&st=2019-06-25T19%3A27%3A18Z&se=2019-07-26T19%3A32%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by clineer** [comment]
Thanks Mandi! I was out in Seattle this week for the BizTalk360 conference and had some corrections for the WCF relay articles over on Azure Docs too.

**Comment by clineer** [comment]
I was not sure if the en-us (https://docs.microsoft.com/en-us/biztalk/core/logic-app-adapter) localized URL was a separate page to update or not. I can update that one too if it is separate. Thanks, Ben

**Comment by MandiOhlinger** [comment]
@clineer You're good. Localization happens automatically from this master branch.

**Comment by clineer** [comment]
Mandi, does the article update eventually? It did not appear to update after the merge.

**Comment by MandiOhlinger** [comment]
It's updated in the Master branch, but not the Live branch yet. I have a few other PRs to review. Once they're done, I'll merge the changes from Master to Live.

**Comment by clineer** [comment]
Ok that makes sense, thank you!

Ben

**Pull request merged**
