### PR TITLE
Update step-7-create-a-sample-lob-message.md

### PR DESCRIPTION
**Pull request by sandroasp**
Fixing the path of LOBApplication tool

### CODE REVIEW

**Comment by sandroasp** [comment]
Making new changes

**Comment by sandroasp** [comment]
All changes made

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/accelerator-rosettanet/step-7-create-a-sample-lob-message.md](https://github.com/sandroasp/biztalk-docs/blob/patch-25/biztalk/adapters-and-accelerators/accelerator-rosettanet/step-7-create-a-sample-lob-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/accelerator-rosettanet/step-7-create-a-sample-lob-message?branch=pr-en-us-224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C23%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201805231014469073-224%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Y6ah25%2F%2BOMJuopsuDbcWIhPYwPq5Q2Pv%2BNlHnuDyL7w%3D&st=2018-05-23T10%3A12%3A55Z&se=2018-06-23T10%3A17%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/accelerator-rosettanet/step-7-create-a-sample-lob-message.md](https://github.com/sandroasp/biztalk-docs/blob/patch-25/biztalk/adapters-and-accelerators/accelerator-rosettanet/step-7-create-a-sample-lob-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/accelerator-rosettanet/step-7-create-a-sample-lob-message?branch=pr-en-us-224) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C23%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201805231017517794-224%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XpXq23KKNF21q9HALa417Qp8gT34wcZRL0JHQvj4Wns%3D&st=2018-05-23T10%3A16%3A32Z&se=2018-06-23T10%3A21%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
