### PR TITLE
L20437: Character in file name casusing localiztion problems

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @gplarsen,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.  The character ' in the file name is breaking target format.
  
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.

Many thanks in advance.

### CODE REVIEW

**Comment by carolinacmoravia** [comment]
Hello, @gplarsen,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version. The character ' in the file name is breaking target format.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.

**Comment by carolinacmoravia** [comment]
Hello, @gplarsen,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version. The character ' in the file name is breaking target format.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.

**Comment by carolinacmoravia** [comment]
Hello, @gplarsen,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version. The character ' in the file name is breaking target format.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.
Cc: @ishasahni1

**Comment by carolinacmoravia** [comment]
Hello, @gplarsen,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version. The character ' in the file name is breaking target format.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.
Cc: @ishasahni1 @v-maudel

**Comment by v-maudel** [comment]
Hello, @gplarsen ,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version. The character ' in the file name is breaking target format.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.

Many thanks in advance.
Cc: @ishasahni1 @carolinacmoravia

**Comment by carolinacmoravia** [comment]
Closing this PR since Loc Ticket has been resolved.

**Pull request closed without merging**
