### PR TITLE
Linkfix: Biztalk (2021-06) - 10

### PR DESCRIPTION
**Pull request by v-kents**
Split with Split-GitChanges

### CODE REVIEW

**Comment by v-kents** [comment]
#sign-off (bulk updates to links)

**Comment by MandiOhlinger** [comment]
Note to myself: Once build issues are resolved, and pending no conflicts, PR is ready to merge.

**Comment by v-kents** [comment]
reopening as that error has been fixed

**Comment by v-kents** [comment]
#sign-off (bulk updates to links)

**Pull request merged**
