### PR TITLE
Update hardware-and-software-requirements-for-biztalk-server-2013-and…

### PR DESCRIPTION
**Pull request by sandroasp**
…-2013-r2.md

remove SharePoint it is not a requirement and it never was

### CODE REVIEW

**Comment by Pacort** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2013-and-2013-r2.md](https://github.com/sandroasp/biztalk-docs/blob/patch-9/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2013-and-2013-r2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/install-and-config-guides/hardware-and-software-requirements-for-biztalk-server-2013-and-2013-r2?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C27%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201709272332116089-73%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jINBGt9rQUq3XC2cqABiyEXHIcn2OPrZNWxJuoS2lLY%3D&st=2017-09-27T23%3A29%3A31Z&se=2017-09-28T23%3A39%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@sandroasp  We can't remove the SharePoint supported versions, but I get what you're saying. What if we change "Software requirements" to "Supported software versions"? We can do this for the 2016 and 2013/R2 topics.

**Comment by sandroasp** [comment]
That is better, but in that case you should also specify for the rest of the product: SAP, Oracle, and so on

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MandiOhlinger** [comment]
Closing without merging. I updated the header to say "supported versions", and added link to supported LOB systems.

**Pull request closed without merging**
