### PR TITLE
Update install-biztalk-adapter-pack-2013-r2-and-2013.md

### PR DESCRIPTION
**Pull request by john-par**
Updated formatting per User Story 1571029: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1571029

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[61546b9](https://github.com/john-par/biztalk-docs/pull/426/commits/61546b955d23a8089b9ff5f29fb80d0817e88d4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md](https://github.com/john-par/biztalk-docs/blob/patch-1/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013?branch=pr-en-us-426) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C1%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201908012319391385-426%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KD5HxoxrEN5Mbe1%2F%2Fm1YFgQZYDJ5yaSVuYu4hHP62nw%3D&st=2019-08-01T23%3A18%3A28Z&se=2019-09-01T23%3A23%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by john-par** [comment]
Minor formatting update related to [User Story 1571029](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1571029).

#sign-off

**Comment by john-par** [comment]
@tfosmark I signed-off on this Loc-fix PR yesterday, but it hasn't been reviewed. This is the first time I'm working in the biztalk-docs repo and I'm not sure if the workflow is different here than in other repos. Do you have the power to move the review process along?

**Comment by john-par** [comment]
Closing pull request because it was made, in error, against the **live** branch. I have recreated the updates in [PR427](https://github.com/MicrosoftDocs/biztalk-docs/pull/427) which I made against the **master** branch.

**Pull request closed without merging**
