### PR TITLE
Update install-biztalk-adapter-pack-2013-r2-and-2013.md

### PR DESCRIPTION
**Pull request by john-par**
Updated formatting per User Story 1571029: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1571029

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[f74a710](https://github.com/john-par/biztalk-docs/pull/427/commits/f74a710bf5a741cadf6d2e45419804b2e126c8a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md](https://github.com/john-par/biztalk-docs/blob/patch-2/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013?branch=pr-en-us-427) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C2%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201908021727232641-427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zeSf7olQEh6JBKlsDYrmOzDoCfl5PcxIGEEZ3wKoAa8%3D&st=2019-08-02T17%3A25%3A58Z&se=2019-09-02T17%3A30%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[d555d20](https://github.com/john-par/biztalk-docs/pull/427/commits/d555d20ff507b5540986f586f6aa17089dc60c5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md](https://github.com/john-par/biztalk-docs/blob/patch-2/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/adapters-and-accelerators/install-biztalk-adapter-pack-2013-r2-and-2013?branch=pr-en-us-427) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C2%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201908021736488872-427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zg1cxvwmQEXf2DziXjlrDYqSdLRPCRSbz3WYDPaEt2k%3D&st=2019-08-02T17%3A35%3A27Z&se=2019-09-02T17%3A40%3A27Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by john-par** [comment]
@MandiOhlinger this PR against the **master** branch is ready for your review. I closed [the other PR](https://github.com/MicrosoftDocs/biztalk-docs/pull/426) against the **live** branch. Sorry for the confusion.

Minor formatting update related to [User Story 1571029](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1571029).

#sign-off

**Comment by john-par** [comment]
@MandiOhlinger this PR is ready to merge.

**Comment by john-par** [comment]
The issue was already fixed under [PR424](https://github.com/MicrosoftDocs/biztalk-docs/pull/424). Since that Pull Request was created first, I am closing this one as redundant and unnecessary.

**Pull request closed without merging**
