### PR TITLE
Update read-about-biztalk-adapter-for-mysap-business-suite-binding-pr…

### PR DESCRIPTION
**Pull request by eprofeta**
…operties.md

### CODE REVIEW

**Comment by Erikre** [comment]
In the future, we should add (or re-add) the following metadata to the file:
description: "Read about BizTalk Adapter for mySAP Business Suite binding properties"

**Comment by Erikre** [comment]
Additions look good. I'm signing off for the author/owner of this topic. #sign-off

**Comment by Erikre** [comment]
#hold-off

**Comment by MandiOhlinger** [comment]
@eprofeta This PR is in the Sandbox repo, which isn't used for PRs. We need to make this change in the Master repo. I'm comparing the changes, and don't see what was actually changed.

Can you make this change in the Master repo? Also, what specifically did you change?

**Comment by MandiOhlinger** [comment]
Closing PR w/o merging. New PR was created in main branch.

**Pull request closed without merging**
