### PR TITLE
C75240: Adding missing asterisk

### PR DESCRIPTION
**Pull request by v-makoud**
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[6080d09](https://github.com/v-makoud/biztalk-docs/pull/389/commits/6080d09525119467e6a0907842f2625cd30f5dd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/dehydration-default-properties.md](https://github.com/v-makoud/biztalk-docs/blob/patch-12/biztalk/core/dehydration-default-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/dehydration-default-properties?branch=pr-en-us-389) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C3%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201904031150309667-389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nvC1YDjpbG%2F9PAwbICh0hBFe29jEwttfbV3IH%2F%2FPlPI%3D&st=2019-04-03T11%3A49%3A36Z&se=2019-05-04T11%3A54%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-makoud** [comment]
#sign-off

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[502198a](https://github.com/v-makoud/biztalk-docs/pull/389/commits/502198a3e4431d12cea57420d8c1c02fdea6ba60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/dehydration-default-properties.md](https://github.com/v-makoud/biztalk-docs/blob/patch-12/biztalk/core/dehydration-default-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/dehydration-default-properties?branch=pr-en-us-389) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C3%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201904031210025668-389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lpthbSY0YWeqzUSAC7qvgwY6oanN2XOv%2BMnQRs9bZc4%3D&st=2019-04-03T12%3A08%3A56Z&se=2019-05-04T12%3A13%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[848b0d6](https://github.com/v-makoud/biztalk-docs/pull/389/commits/848b0d6fb53bcc0392bf7dfe651ecefd23375c21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/dehydration-default-properties.md](https://github.com/v-makoud/biztalk-docs/blob/patch-12/biztalk/core/dehydration-default-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/dehydration-default-properties?branch=pr-en-us-389) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C3%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201904031219098909-389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9aj2KbT%2FCC9hXy09wuY6IvBOiljqQot5XBtCZwpqq6Y%3D&st=2019-04-03T12%3A18%3A21Z&se=2019-05-04T12%3A23%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[3acd472](https://github.com/v-makoud/biztalk-docs/pull/389/commits/3acd472830449e5202b792c79e1911a6e65e8215)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/dehydration-default-properties.md](https://github.com/v-makoud/biztalk-docs/blob/patch-12/biztalk/core/dehydration-default-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/dehydration-default-properties?branch=pr-en-us-389) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C3%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201904031224485907-389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MU%2B%2FJqWt17FQWTabbMbKNyDTVHdn3hLHDQg4bd9dbAc%3D&st=2019-04-03T12%3A23%3A46Z&se=2019-05-04T12%3A28%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
