### PR TITLE
[BrokenLinksH2] Fixed broken links

### PR DESCRIPTION
**Pull request by kturetz**
Fixed broken links in biztalk documents.

### CODE REVIEW

**Comment by kturetz** [comment]
**Global effort to fix broken links** 

@ChristopherHouser 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I’d very much appreciate your timely review and feedback on the link changes I’ve suggested. Thanks!

**Comment by ChristopherHouser** [comment]
So the in the Previews, the links in grey have been deleted (as they no longer exist)?   That is fine.

**Comment by kturetz** [comment]
> So in the Previews, the links in grey have been deleted (as they no longer exist)? That is fine.

Thanks, Christopher. In many cases when we are unable to find a replacement link, we comment out the existing link with backticks.

**Comment by MandiOhlinger** [comment]
Closing this PR w/o merging. Replacing links with code blocks isn't a good option. I removed the broken links in https://github.com/MicrosoftDocs/biztalk-docs/pull/799.

**Pull request closed without merging**
