### PR TITLE
Deprecated features in SQL Server 2016

### PR DESCRIPTION
**Pull request by tcanter**
SQL Server deprecated features will make the Restore Process fail in a non-obvious fashion. The proposed change will lead the user here by including the explicit error message. The content shows the user what file to change and what to change it to.

### CODE REVIEW

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-restore-your-databases.md](https://github.com/tcanter/biztalk-docs/blob/patch-1/biztalk/core/how-to-restore-your-databases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-restore-your-databases?branch=pr-en-us-262) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C28%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201806280047326196-262%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Dsu56sZ8mN09Mfv8WE4s%2BQBLNnaUVktHjAmv18pf70Y%3D&st=2018-06-28T00%3A45%3A51Z&se=2018-07-29T00%3A50%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
@tcanter Thank you very much. Is the new provider correct? It seems like there's a typo, as there's just an extra "D" in the new provider. 

Old: SQLOLEDB
New: SQLOLEDDB

**Comment by MandiOhlinger** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-restore-your-databases.md](https://github.com/tcanter/biztalk-docs/blob/patch-1/biztalk/core/how-to-restore-your-databases.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/biztalk/core/how-to-restore-your-databases?branch=pr-en-us-262) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C28%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201806281304571816-262%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qV%2BmFf8cGJ0IdKLTEweeL9VzduBCxd2A7VtE8X5geH0%3D&st=2018-06-28T13%3A03%3A51Z&se=2018-07-29T13%3A08%3A51Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by tcanter** [comment]
In addition, the longer term SQL OLD DB Driver isn't included and must be downloaded from https://www.microsoft.com/en-us/download/details.aspx?id=56730

This means the article needs to reference this download and tell the user to install it...

https://blogs.msdn.microsoft.com/sqlnativeclient/2018/03/30/released-microsoft-ole-db-driver-for-sql-server/

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[d74f939](https://github.com/tcanter/biztalk-docs/pull/262/commits/d74f9398a48684d12845e843cba57c090eabe8e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-restore-your-databases.md](https://github.com/tcanter/biztalk-docs/blob/patch-1/biztalk/core/how-to-restore-your-databases.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C22%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201904221825051771-262%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=v%2FPlOdo7XUoZRqtcp97424Mti9pCJHe75dblWwPfXIA%3D&st=2019-04-22T18%3A24%3A12Z&se=2019-05-23T18%3A29%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MandiOhlinger** [comment]
Docs Build status updates of commit _[a7e2bae](https://github.com/tcanter/biztalk-docs/pull/262/commits/a7e2baef618bfeb68dabd56a176a9a6509ed10e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[biztalk/core/how-to-restore-your-databases.md](https://github.com/tcanter/biztalk-docs/blob/patch-1/biztalk/core/how-to-restore-your-databases.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C22%5C1068b9ca-0f6f-8159-0900-54ef27790f1e%5CPullRequest%5C201904222102335865-262%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TqtKQdFV8U0TtPGAgSmCy4aIYO0ZcTD5J3B%2Fs%2Be1ENc%3D&st=2019-04-22T21%3A01%3A32Z&se=2019-05-23T21%3A06%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
